server.port=8081
server.servlet.context-path=/
spring.application.name=collaborative-java-workspace-backend

backend.events.enabled=true
backend.events.port=9091
backend.rmi.enabled=true
backend.rmi.host=127.0.0.1
backend.rmi.port=1099
backend.rmi.service-name=JavaWorkspaceAnalysisService

management.endpoints.web.exposure.include=health,info
